### PR TITLE
Fix bug in Hall Of Fame. Fix #65.

### LINKED ISSUE #65: Hall Of Fame - Novo User
Ao criar um novo utilizador, o número de badges no _Hall of Fame_ aparece _buggado_ não aparecendo o número de badges inicial, ou seja, zero. Envio uma imagem que ilustra o que acabei de escrever. 
bug

### PR DESCRIPTION
**Pull request by dinocosta**
- Fix a bug where a user with no badges would not have 0 badges in hall
of fame. This is due to the fact that `badge_acquisitions_count` is nil
when the user has no badges.
- Create ParticipantsHelper with two helpers `hall_of_fame_title` and
`participant_badge_count`.

### CODE REVIEW

File: app/helpers/participants_helper.rb [hunk 1]
```diff
@@ -0,0 +1,9 @@
+module ParticipantsHelper
+  def hall_of_fame_title
+    params[:action] == "hall_of_fame" ? "Hall Of Fame" : "Organizer Of Fame"
+  end
+
+  def participant_badge_count(participant)
+    participant.badge_acquisitions_count == nil ? 0 : participant.badge_acquisitions_count
```
Comment (frm) [inline app/helpers/participants_helper.rb]: Or

```ruby
participant.badge_acquisitions_count || 0
```

**Review by frm — CHANGES_REQUESTED** [review]

File: app/helpers/participants_helper.rb (hunk 1 above)
Comment (dinocosta) [reply app/helpers/participants_helper.rb]: 👍

**Review by dinocosta — COMMENTED** [review]
@frmendes Updated.

**Review by frm — APPROVED** [review]
